
package com.brandmaker.webservices.theme;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ThemeWebServicePort", targetNamespace = "http://brandmaker.com/webservices/Theme/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ThemeWebServicePort {


    /**
     * 
     * @param themeId
     * @return
     *     returns com.brandmaker.webservices.theme.ThemesResult
     * @throws ThemeWebServiceFault_Exception
     */
    @WebMethod(action = "getSortedThemeTree")
    @WebResult(name = "theme", targetNamespace = "http://brandmaker.com/webservices/Theme/")
    @RequestWrapper(localName = "getSortedThemeTree", targetNamespace = "http://brandmaker.com/webservices/Theme/", className = "com.brandmaker.webservices.theme.GetSortedThemeTree")
    @ResponseWrapper(localName = "getSortedThemeTreeResponse", targetNamespace = "http://brandmaker.com/webservices/Theme/", className = "com.brandmaker.webservices.theme.GetSortedThemeTreeResponse")
    ThemesResult getSortedThemeTree(
            @WebParam(name = "themeId", targetNamespace = "http://brandmaker.com/webservices/Theme/")
                    Integer themeId)
        throws ThemeWebServiceFault_Exception
    ;

    /**
     * 
     * @param theme
     * @return
     *     returns com.brandmaker.webservices.theme.ThemeResult
     * @throws ThemeWebServiceFault_Exception
     */
    @WebMethod(action = "createSortedTheme")
    @WebResult(name = "result", targetNamespace = "http://brandmaker.com/webservices/Theme/")
    @RequestWrapper(localName = "createSortedTheme", targetNamespace = "http://brandmaker.com/webservices/Theme/", className = "com.brandmaker.webservices.theme.CreateSortedTheme")
    @ResponseWrapper(localName = "createSortedThemeResponse", targetNamespace = "http://brandmaker.com/webservices/Theme/", className = "com.brandmaker.webservices.theme.CreateSortedThemeResponse")
    ThemeResult createSortedTheme(
            @WebParam(name = "theme", targetNamespace = "http://brandmaker.com/webservices/Theme/")
                    Theme theme)
        throws ThemeWebServiceFault_Exception
    ;

    /**
     * 
     * @param themeId
     * @return
     *     returns com.brandmaker.webservices.theme.ThemesResult
     * @throws ThemeWebServiceFault_Exception
     */
    @WebMethod(action = "getDetailedSortedThemeTree")
    @WebResult(name = "theme", targetNamespace = "http://brandmaker.com/webservices/Theme/")
    @RequestWrapper(localName = "getDetailedSortedThemeTree", targetNamespace = "http://brandmaker.com/webservices/Theme/", className = "com.brandmaker.webservices.theme.GetDetailedSortedThemeTree")
    @ResponseWrapper(localName = "getDetailedSortedThemeTreeResponse", targetNamespace = "http://brandmaker.com/webservices/Theme/", className = "com.brandmaker.webservices.theme.GetDetailedSortedThemeTreeResponse")
    ThemesResult getDetailedSortedThemeTree(
            @WebParam(name = "themeId", targetNamespace = "http://brandmaker.com/webservices/Theme/")
                    Integer themeId)
        throws ThemeWebServiceFault_Exception
    ;

    /**
     * 
     * @param theme
     * @return
     *     returns com.brandmaker.webservices.theme.ThemeResult
     * @throws ThemeWebServiceFault_Exception
     */
    @WebMethod(action = "createTheme")
    @WebResult(name = "result", targetNamespace = "http://brandmaker.com/webservices/Theme/")
    @RequestWrapper(localName = "createTheme", targetNamespace = "http://brandmaker.com/webservices/Theme/", className = "com.brandmaker.webservices.theme.CreateTheme")
    @ResponseWrapper(localName = "createThemeResponse", targetNamespace = "http://brandmaker.com/webservices/Theme/", className = "com.brandmaker.webservices.theme.CreateThemeResponse")
    ThemeResult createTheme(
            @WebParam(name = "theme", targetNamespace = "http://brandmaker.com/webservices/Theme/")
                    Theme theme)
        throws ThemeWebServiceFault_Exception
    ;

    /**
     * 
     * @param theme
     * @return
     *     returns boolean
     * @throws ThemeWebServiceFault_Exception
     */
    @WebMethod(action = "updateThemeById")
    @WebResult(name = "result", targetNamespace = "http://brandmaker.com/webservices/Theme/")
    @RequestWrapper(localName = "updateThemeById", targetNamespace = "http://brandmaker.com/webservices/Theme/", className = "com.brandmaker.webservices.theme.UpdateThemeById")
    @ResponseWrapper(localName = "updateThemeByIdResponse", targetNamespace = "http://brandmaker.com/webservices/Theme/", className = "com.brandmaker.webservices.theme.UpdateThemeByIdResponse")
    boolean updateThemeById(
            @WebParam(name = "theme", targetNamespace = "http://brandmaker.com/webservices/Theme/")
                    Theme theme)
        throws ThemeWebServiceFault_Exception
    ;

    /**
     * 
     * @param themeName
     * @return
     *     returns com.brandmaker.webservices.theme.Theme
     * @throws ThemeWebServiceFault_Exception
     */
    @WebMethod(action = "receiveThemeInformationByPath")
    @WebResult(name = "theme", targetNamespace = "http://brandmaker.com/webservices/Theme/")
    @RequestWrapper(localName = "receiveThemeInformationByPath", targetNamespace = "http://brandmaker.com/webservices/Theme/", className = "com.brandmaker.webservices.theme.ReceiveThemeInformationByPath")
    @ResponseWrapper(localName = "receiveThemeInformationByPathResponse", targetNamespace = "http://brandmaker.com/webservices/Theme/", className = "com.brandmaker.webservices.theme.ReceiveThemeInformationByPathResponse")
    Theme receiveThemeInformationByPath(
            @WebParam(name = "themeName", targetNamespace = "http://brandmaker.com/webservices/Theme/")
                    ThemeName themeName)
        throws ThemeWebServiceFault_Exception
    ;

    /**
     * 
     * @param themeId
     * @return
     *     returns com.brandmaker.webservices.theme.ThemesResult
     * @throws ThemeWebServiceFault_Exception
     */
    @WebMethod(action = "receiveFullThemeTree")
    @WebResult(targetNamespace = "http://brandmaker.com/webservices/Theme/")
    @RequestWrapper(localName = "receiveFullThemeTree", targetNamespace = "http://brandmaker.com/webservices/Theme/", className = "com.brandmaker.webservices.theme.ReceiveFullThemeTree")
    @ResponseWrapper(localName = "receiveFullThemeTreeResponse", targetNamespace = "http://brandmaker.com/webservices/Theme/", className = "com.brandmaker.webservices.theme.ReceiveFullThemeTreeResponse")
    ThemesResult receiveFullThemeTree(
            @WebParam(name = "themeId", targetNamespace = "http://brandmaker.com/webservices/Theme/")
                    Integer themeId)
        throws ThemeWebServiceFault_Exception
    ;

    /**
     * 
     * @param theme
     * @return
     *     returns boolean
     * @throws ThemeWebServiceFault_Exception
     */
    @WebMethod(action = "updateSortedTheme")
    @WebResult(name = "result", targetNamespace = "http://brandmaker.com/webservices/Theme/")
    @RequestWrapper(localName = "updateSortedTheme", targetNamespace = "http://brandmaker.com/webservices/Theme/", className = "com.brandmaker.webservices.theme.UpdateSortedTheme")
    @ResponseWrapper(localName = "updateSortedThemeResponse", targetNamespace = "http://brandmaker.com/webservices/Theme/", className = "com.brandmaker.webservices.theme.UpdateSortedThemeResponse")
    boolean updateSortedTheme(
            @WebParam(name = "theme", targetNamespace = "http://brandmaker.com/webservices/Theme/")
                    Theme theme)
        throws ThemeWebServiceFault_Exception
    ;

    /**
     * 
     * @param themeId
     * @return
     *     returns boolean
     * @throws ThemeWebServiceFault_Exception
     */
    @WebMethod(action = "deleteThemeById")
    @WebResult(name = "result", targetNamespace = "http://brandmaker.com/webservices/Theme/")
    @RequestWrapper(localName = "deleteThemeById", targetNamespace = "http://brandmaker.com/webservices/Theme/", className = "com.brandmaker.webservices.theme.DeleteThemeById")
    @ResponseWrapper(localName = "deleteThemeByIdResponse", targetNamespace = "http://brandmaker.com/webservices/Theme/", className = "com.brandmaker.webservices.theme.DeleteThemeByIdResponse")
    boolean deleteThemeById(
            @WebParam(name = "themeId", targetNamespace = "http://brandmaker.com/webservices/Theme/")
                    Integer themeId)
        throws ThemeWebServiceFault_Exception
    ;

    /**
     * 
     * @param themeId
     * @return
     *     returns com.brandmaker.webservices.theme.ThemesResult
     * @throws ThemeWebServiceFault_Exception
     */
    @WebMethod(action = "receiveFullThemeTreeInformation")
    @WebResult(targetNamespace = "http://brandmaker.com/webservices/Theme/")
    @RequestWrapper(localName = "receiveFullThemeTreeInformation", targetNamespace = "http://brandmaker.com/webservices/Theme/", className = "com.brandmaker.webservices.theme.ReceiveFullThemeTreeInformation")
    @ResponseWrapper(localName = "receiveFullThemeTreeInformationResponse", targetNamespace = "http://brandmaker.com/webservices/Theme/", className = "com.brandmaker.webservices.theme.ReceiveFullThemeTreeInformationResponse")
    ThemesResult receiveFullThemeTreeInformation(
            @WebParam(name = "themeId", targetNamespace = "http://brandmaker.com/webservices/Theme/")
                    Integer themeId)
        throws ThemeWebServiceFault_Exception
    ;

    /**
     * 
     * @param themeId
     * @return
     *     returns com.brandmaker.webservices.theme.Theme
     * @throws ThemeWebServiceFault_Exception
     */
    @WebMethod(action = "receiveThemeInformationById")
    @WebResult(name = "theme", targetNamespace = "http://brandmaker.com/webservices/Theme/")
    @RequestWrapper(localName = "receiveThemeInformationById", targetNamespace = "http://brandmaker.com/webservices/Theme/", className = "com.brandmaker.webservices.theme.ReceiveThemeInformationById")
    @ResponseWrapper(localName = "receiveThemeInformationByIdResponse", targetNamespace = "http://brandmaker.com/webservices/Theme/", className = "com.brandmaker.webservices.theme.ReceiveThemeInformationByIdResponse")
    Theme receiveThemeInformationById(
            @WebParam(name = "themeId", targetNamespace = "http://brandmaker.com/webservices/Theme/")
                    Integer themeId)
        throws ThemeWebServiceFault_Exception
    ;

}
