
package com.brandmaker.webservices.theme;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ThemeService", targetNamespace = "http://brandmaker.com/webservices/Theme/", wsdlLocation = "https://qamarriott.brandmakerinc.com/webservices/Theme/?wsdl")
public class ThemeService
    extends Service
{

    private final static URL THEMESERVICE_WSDL_LOCATION;
    private final static WebServiceException THEMESERVICE_EXCEPTION;
    private final static QName THEMESERVICE_QNAME = new QName("http://brandmaker.com/webservices/Theme/", "ThemeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://qamarriott.brandmakerinc.com/webservices/Theme/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        THEMESERVICE_WSDL_LOCATION = url;
        THEMESERVICE_EXCEPTION = e;
    }

    public ThemeService() {
        super(__getWsdlLocation(), THEMESERVICE_QNAME);
    }

    public ThemeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns ThemeWebServicePort
     */
    @WebEndpoint(name = "ThemePort")
    public ThemeWebServicePort getThemePort() {
        return super.getPort(new QName("http://brandmaker.com/webservices/Theme/", "ThemePort"), ThemeWebServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ThemeWebServicePort
     */
    @WebEndpoint(name = "ThemePort")
    public ThemeWebServicePort getThemePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://brandmaker.com/webservices/Theme/", "ThemePort"), ThemeWebServicePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (THEMESERVICE_EXCEPTION!= null) {
            throw THEMESERVICE_EXCEPTION;
        }
        return THEMESERVICE_WSDL_LOCATION;
    }

}
