
package com.brandmaker.webservices.mediapool;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MediaPoolService_v2", targetNamespace = "http://brandmaker.com/webservices/MediaPool/v2/", wsdlLocation = "https://qamarriott.brandmakerinc.com/webservices/MediaPool/v2/?wsdl")
public class MediaPoolServiceV2
    extends Service
{

    private final static URL MEDIAPOOLSERVICEV2_WSDL_LOCATION;
    private final static WebServiceException MEDIAPOOLSERVICEV2_EXCEPTION;
    private final static QName MEDIAPOOLSERVICEV2_QNAME = new QName("http://brandmaker.com/webservices/MediaPool/v2/", "MediaPoolService_v2");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://qamarriott.brandmakerinc.com/webservices/MediaPool/v2/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MEDIAPOOLSERVICEV2_WSDL_LOCATION = url;
        MEDIAPOOLSERVICEV2_EXCEPTION = e;
    }

    public MediaPoolServiceV2() {
        super(__getWsdlLocation(), MEDIAPOOLSERVICEV2_QNAME);
    }

    public MediaPoolServiceV2(WebServiceFeature... features) {
        super(__getWsdlLocation(), MEDIAPOOLSERVICEV2_QNAME, features);
    }

    public MediaPoolServiceV2(URL wsdlLocation) {
        super(wsdlLocation, MEDIAPOOLSERVICEV2_QNAME);
    }

    public MediaPoolServiceV2(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MEDIAPOOLSERVICEV2_QNAME, features);
    }

    public MediaPoolServiceV2(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MediaPoolServiceV2(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MediaPoolWebServicePortV2
     */
    @WebEndpoint(name = "MediaPoolPort_v2")
    public MediaPoolWebServicePortV2 getMediaPoolPortV2() {
        return super.getPort(new QName("http://brandmaker.com/webservices/MediaPool/v2/", "MediaPoolPort_v2"), MediaPoolWebServicePortV2.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MediaPoolWebServicePortV2
     */
    @WebEndpoint(name = "MediaPoolPort_v2")
    public MediaPoolWebServicePortV2 getMediaPoolPortV2(WebServiceFeature... features) {
        return super.getPort(new QName("http://brandmaker.com/webservices/MediaPool/v2/", "MediaPoolPort_v2"), MediaPoolWebServicePortV2.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MEDIAPOOLSERVICEV2_EXCEPTION!= null) {
            throw MEDIAPOOLSERVICEV2_EXCEPTION;
        }
        return MEDIAPOOLSERVICEV2_WSDL_LOCATION;
    }

}
