
package com.brandmaker.webservices.mediapool;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "MediaPoolService", targetNamespace = "http://brandmaker.com/webservices/MediaPool/", wsdlLocation = "https://qamarriott.brandmakerinc.com/webservices/MediaPool/?wsdl")
public class MediaPoolService
    extends Service
{

    private final static URL MEDIAPOOLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MEDIAPOOLSERVICE_EXCEPTION;
    private final static QName MEDIAPOOLSERVICE_QNAME = new QName("http://brandmaker.com/webservices/MediaPool/", "MediaPoolService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://qamarriott.brandmakerinc.com/webservices/MediaPool/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MEDIAPOOLSERVICE_WSDL_LOCATION = url;
        MEDIAPOOLSERVICE_EXCEPTION = e;
    }

    public MediaPoolService() {
        super(__getWsdlLocation(), MEDIAPOOLSERVICE_QNAME);
    }

    public MediaPoolService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns MediaPoolWebServicePort
     */
    @WebEndpoint(name = "MediaPoolPort")
    public MediaPoolWebServicePort getMediaPoolPort() {
        return super.getPort(new QName("http://brandmaker.com/webservices/MediaPool/", "MediaPoolPort"), MediaPoolWebServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MediaPoolWebServicePort
     */
    @WebEndpoint(name = "MediaPoolPort")
    public MediaPoolWebServicePort getMediaPoolPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://brandmaker.com/webservices/MediaPool/", "MediaPoolPort"), MediaPoolWebServicePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MEDIAPOOLSERVICE_EXCEPTION!= null) {
            throw MEDIAPOOLSERVICE_EXCEPTION;
        }
        return MEDIAPOOLSERVICE_WSDL_LOCATION;
    }

}
