/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MediaPoolMalBridge;


import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
//@EnableJpaRepositories("MediaPoolMalBridge.persistence.repository")
//@EntityScan("MediaPoolMALBridge.persistence.entity")
public class App {

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }

}


